### ISSUE TITLE
komorebi widgets not working

### ISSUE THREAD

**Issue by Bcez** [denBot/yasb#48]
ive followed what to do on the page but i get this error 

Starting KomorebiEventListener...
Created named pipe yasb-c44170f9-1f49-11ed-b703-5cf3707bf232
Waiting for Komorebi to subscribe to named pipe yasb-c44170f9-1f49-11ed-b703-5cf3707bf232
Created file watcher for path C:\Users\eric\.yasb
Komorebi failed to subscribe named pipe. Waiting for subscription: 'komorebic.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chaitanya02082000** [comment]
add komorebi install in the PATH
